const list = [
  {
    id: 1,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 2,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 3,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 4,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 5,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 6,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 7,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 8,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 9,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 10,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 11,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 12,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 13,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 14,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
  {
    id: 15,
    name: "Harshit P G",
    rank: "0600",
    block: "B,Q,L,M",
    bed: "2,3,4,6",
    year: 2023,
    gender: "Boy",
  },
];

export default list;
